spring.application.name=IDFTransports
spring.config.import=optional:file:./.env[.properties]

# Desactive le lancement automatique du job au demarrage
spring.batch.job.enabled=true
spring.batch.job.name=importStopTimesJob

# Initialise automatiquement le schema de metadonnees Spring Batch
spring.batch.jdbc.initialize-schema=always

# Initalisation du schema
spring.sql.init.mode=always

# Connexion
spring.datasource.url=jdbc:postgresql://localhost:5432/transport?reWriteBatchedInserts=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Initialisation de la base
spring.sql.init.schema-locations=classpath:schema.sql
spring.datasource.hikari.schema=public